[package]
name = "exfiltrate_proxy"
version.workspace = true
edition.workspace = true

[[bin]]
name = "exfiltrate_proxy"
path = "src/main.rs"

[dependencies]
exfiltrate-internal.workspace = true
sha1 = "0.10.6"
base64 = "0.22.1"
